### ISSUE TITLE
Small Grammer suggestions

### ISSUE THREAD

**Issue by Murph45** [myersj451/myersj451.github.io#5]
In the second paragraph you need a "the" before desktop, the "s" in safe search should be capitalized, another "the" before spotlight in the third paragraph. In the forth paragraph i think you meant "Riding" instead of "Ridding", I would suggest adding "an" before effort in the same paragraph so that it adds flow. The final paragraph add another the before "fake news".

**Comment by myersj451** [comment]
Thank you for the corrections
