### ISSUE TITLE
Grammer issues that interrupt 

### ISSUE THREAD

**Issue by Murph45** [myersj451/myersj451.github.io#8]
misniscle -> minuscle

repeated "the" twice "blaring from the the radio is "

" the world do not give second thought to." -> a second thought

"whether legal or pirated," -> no comma is needed

**Comment by Murph45** [comment]
I would try to incorporate transitional words when Brian and Ethan say something that sounds alike for example when then talk about how piracy hurts artist. It would help to tie the ideas in together more

**Comment by myersj451** [comment]
Thank you for the suggestions
